name: DNS on Try

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Hesoyam
        path: D:\a\DNS-on-Try\DNS-on-Try\DNS on Try\bin\Debug\net8.0-windows\DNS on Try.dll
      
